server:
  port: 10001
spring:
  application:
    name: news-admin-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 172.25.41.55:8848
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      routes:
      # 平台管理
      - id: admin
        uri: lb://news-admin
        predicates: # 断言  判断是否满足路由的条件
        - Path=/admin/**
        filters: # 当前路由对应的过滤器
        - StripPrefix= 1 # 去除路径前缀
      # 平台管理
      - id: user
        uri: lb://news-user
        predicates: # 断言  判断是否满足路由的条件
        - Path=/user/**
        filters: # 当前路由对应的过滤器
        - StripPrefix= 1 # 去除路径前 缀