server:
  port: 9001
spring:
  application:
    name: news-admin
  datasource:
    url: jdbc:mysql://172.25.41.55:3307/leadnews_admin?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
#    data-username: root
#    data-password: root
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: 172.25.41.55:8848
    inetutils:
      timeout-seconds: 3
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.fiume.model.admin.pojos
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl